<div id='result<?php echo $this->course->getId() ?>'></div>
<?php echo CHtml::form(); ?>

<table>
	<thead>
		<tr>
			<th>Step</th>
			<th>Current Progress</th>
			<th>Marks</th>
		</tr>
	</thead>
	<?php foreach($this->course->getSteps() as $step):?>
		<tr>
			<td>
				<a href="<?php echo \Yii::app()->createUrl('/lms/user/marks/default/step', array('userID' => $this->student->getId(), 'id' => $step->getId())) ?>">
				<?php echo $step->getName(); ?>
				</a>
			</td>
			<td>
				<?php $this->widget('zii.widgets.jui.CJuiProgressBar',array(
					'value' => $this->studentProgress[$step->getId()],
					'htmlOptions'=>array(
						'style'=>'height:10px;',
					),
				));
				?>
			</td>
			<td>
				<?php if($this->isAdmin): ?>
					<?php echo CHtml::numberField('Marks['.$step->getId().']', $this->marks[$step->getId()], array('style'=>'width:40px;')) ?>
				<?php else: ?>
					<?php echo $this->marks[$step->getId()]; ?>
				<?php endif; ?>
			</td>
		</tr>
	<?php endforeach; ?>
</table>

<?php
if($this->isAdmin){
	echo CHtml::ajaxSubmitButton('Save', \Yii::app()->createUrl('/lms/user/marks/default/save', array('userID' => $this->student->getId())), array(
			'type' => 'POST',
			'update' => '#result'.$this->course->getId().'',
			'beforeSend'=>'js:function(data){
				$("#result'.$this->course->getId().'").text("Saving...");
				$("#result'.$this->course->getId().'").slideDown();
			}',
			'success' => 'function(response) {
				$("#result'.$this->course->getId().'").text(response);
				setTimeout(function(){
					$("#result'.$this->course->getId().'").slideUp();
				}, 2000);
			}',
		),
		array(
			'type' => 'submit'
		));
}
echo CHtml::endForm();?>

