<script type="text/javascript">
    $(document).ready(function(){
        $("input[name='<?php echo $this->name ?>']").change(function(e){

            var value = $(e.target).val();
            var resultContainer = $('#<?php echo $this->name ?>Container');


            $('#<?php echo $this->name ?>Discriminator').val(value);
            $.ajax({
                url: '<?php echo $this->path ?>',
                type: 'post',
                data: {
                    '<?php echo $this->name ?>': value
                }
            })
            .done(function(data) {
                resultContainer.html(data);
            })
            .fail(function() {
                resultContainer.html('Error occurred');
            });


        });
    });
</script>