<script type='text/javascript'>
    var QuizConfig = {
        baseUrl: "<?php echo $questionsUrl?>",
        baseTemplateUrl : "<?php echo $this->assetUrl . '/templates/'?>"
    };
</script>

<div id='quiz-container' ng-app='quiz'>
    <div ng-controller="QuizQuestionCtrl" data-ng-init='first()'>
        <div id='quiz-navigation' ng-hide='endQuiz'>
			<a href="#" ng-click="prev()">Prev</a>
            <a href="#" ng-click="next()">Next</a>
            <a href="<?php echo $questionsUrl?>/../end" >End Quiz</a>
        </div>

        <div id='quiz-question-loading' style="display: {{loading}}">
            loading...
        </div>

        <div id='quiz-question-result' ng-hide='endQuiz'>
            <div id='quiz-question-result-{{question.result}}'>
                {{question.resultText}}
            </div>
        </div>

        <div id='quiz-question' style="display: {{display}}" ng-hide='endQuiz'>
            <h2>{{question.title}}</h2>
            <div id='question-text'>
                <strong>Question:</strong>{{question.question}}
            </div>
            <div id='question-answer-form' ng-hide='question.done || question.doneEarlier'>
                <ng-include src="question.form"></ng-include>
            </div>
            <div id='question-your-answer' ng-show='question.done && !question.doneEarlier'>
				Your answer: {{question.answers}}
			</div>
			<div id='question-earlier' ng-show='question.doneEarlier'>
				You have already answered this question. Go to the next one
			</div>
        </div>
    </div>
</div>