<div style="width: <?php echo $this->width ?>px">
    <?php $methodGetName = 'get'.$this->nameField ?>
    <?php if(!is_null($this->header) && count($this->items) > 0) : ?>
    	<p><strong><?php echo $this->header ?></strong></p>
    <?php endif; ?>

    <form action="<?php echo $this->path ?>" method="post" name="<?php echo $this->id ?>" id="<?php echo $this->id ?>" >
    <span style='hidden' class='result-order-saving' id="<?php echo $this->id ?>-result"></span>
    <?php ob_start() ?>
		<ol id="<?php echo $this->id ?>-sortable" class="sort-list">
			<?php foreach($this->items as $item): ?>
				<li class="ui-state-default">
					<a href=""><?php echo $item->$methodGetName(); ?></a>
					<input type="hidden" name='order[]' value="<?php echo $item->getID(); ?>" />
				</li>
			<?php endforeach; ?>
		</ol>
    <?php ob_end_flush(); ?>
		<?php if(count($this->items) > 0): ?>
    		<a class="nice-button" onclick="saveOrder('<?php echo $this->id ?>')" >Save</a>
		<?php endif; ?>
    </form>
</div>